import React from 'react';

import Head from 'next/head';

const Playground = () => {
  return (
    <div className="container">
      <Head>
        <title>Playground</title>
        <meta name="Playground" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h3>Hello from home</h3>
      <p>hiiiii</p>
    </div>
  );
};

export default Playground;
