import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from 'react';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Playground</title>
        <meta name="Playground" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h4>Connecting you to server...</h4>
    </div>
  );
}
